version: 2
updates:
  # ===== GRADLE DEPENDENCIES =====
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Santiago"
    reviewers:
      - "DMasterIO"
    assignees:
      - "DMasterIO"
    labels:
      - "dependencies"
      - "gradle"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    ignore:
      # Ignore patch releases of Minecraft/NeoForge - manual control needed
      - dependency-name: "net.neoforged:neoforge"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "net.minecraft:minecraft"
        update-types: ["version-update:semver-patch"]

  # ===== GITHUB ACTIONS =====
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Santiago"
    reviewers:
      - "DMasterIO"
    assignees:
      - "DMasterIO"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3
