modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="empanadaland"
version="1.0.0"
displayName="EmpanadaLand"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ceel2, MCreator"

[[dependencies.empanadaland]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.empanadaland]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.6]"
    ordering="NONE"
    side="BOTH"




